modules/admin/controllers/TaskController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\task\Tasks;
use app\models\task\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\task\AttemptFull;
use app\models\task\Attempts;
use app\models\task\TaskRating;
use app\models\task\UserComplaint;
use app\models\task\UserMessages;
use app\models\task\Tournament;
use app\models\user\User;
use app\models\user\UserPoints;
use yii\filters\AccessControl;
use yii\data\Pagination;

/**
 * TaskController implements the CRUD actions for Tasks model.
 */
class TaskController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST','GET'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCheck()
    {
        $unchecked = AttemptFull::find()->with('attempt')->where(['checked' => null])->asArray()->all();
        return json_encode($unchecked);
    }

    public function actionMessages()
    {   
        $unchecked = AttemptFull::find()->with('attempt')->where(['checked' => null]);

        $countQuery = clone $unchecked;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'defaultPageSize' => 15,
            'forcePageParam' => false, 
            'pageSizeParam' => false,
        ]);
        $models = $unchecked->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy('id DESC')
            ->all();

        return $this->render('messages', [
            'models' => $models,
            'pages' => $pages,
        ]);
    }

    public function actionReadView($id)
    {
        $hold = AttemptFull::find()->with('attempt')->where(['id' => $id])->one();
        $user = User::findOne($hold->attempt->user_id);
        $task = Tasks::findOne($hold->attempt->task_id);
        
        return $this->render('read-view', [
            'hold' => $hold,
            'user' => $user,
            'task' => $task,
        ]);
    }

    

    public function actionComplaintView()
    {
        $complaintId = Yii::$app->request->get('id');
        $complaint = UserComplaint::findOne($complaintId);
        $task = Tasks::findOne($complaint->task_id);
        $user = User::findOne($complaint->user_id);
        if (!empty(Yii::$app->request->get('accept'))) {
            $get = Yii::$app->request->get();
            $compl = UserComplaint::findOne($get['accept']);
            $compl->checked = 1;
            if ($compl->save()) {
                return $this->redirect(['/admin/task/index']);
            }else {
                echo '<pre>';
                print_r('checked column in UserComplaint table does\'t check');
                echo '</pre>';
                exit();
            }
        }

        return $this->render('complaint-view', [
            'complaint' => $complaint,
            'task' => $task,
            'user' => $user,
        ]);
    }

    public function actionUserMessage()
    {
        $user = Yii::$app->user->identity;
        $messages = UserMessages::find()->where(['user_id' => $user->id])->andWhere(['checked' => null])->asArray()->all();
        return json_encode($messages);

    }

    public function actionGetTask($id)
    {
        $task = Tasks::find()->where(['id' => $id])->asArray()->one();
        return json_encode($task);
    }

    public function actionDeleteSend($id)
    {
        $full = AttemptFull::findOne($id);
        $attempt = Attempts::findOne($full->attempt_id);
        $user = User::findOne($attempt->user_id);
        $task = Tasks::findOne($attempt->task_id);
        $task->attempts++;
        $task->save();
        $message = new UserMessages();
        $message->user_id = $attempt->user_id;
        $message->task_id = $attempt->task_id;
        $message->message = "Afsus! $user->username siz javobni to'g'ri topa olmadingiz. Xarakat qiling va to'g'ri javobni toping!";
        $message->date = date('Y-m-d H:i:s');
        $message->save();
        if ($attempt->complete != 1) {
            $full->checked = 1;
            $full->save();
            if ($attempt->attempt > 0) {
                $attempt->attempt--;
                $attempt->save();
            }
            return $this->redirect(['/admin/task/messages']);
        }
        

    }

    public function actionTrueCheck($id)
    {
        $post = Yii::$app->request->post('auto');
        $full = AttemptFull::findOne($id);
        $attempt = Attempts::find()->where(['id' => $full->attempt_id])->one();
        $user = User::findOne($attempt->user_id);
        $task = Tasks::find()->where(['id' => $attempt->task_id])->one();
        $taskMainCat = $task::getMainCat($task->cat_id);
        $userPoint = UserPoints::find()->where(['user_id' => $attempt->user_id])->one();
        if (!empty($full)) {
            $full->true = 1;
            $full->checked = 1;
            if ($post == 'auto') {
                if ($attempt->attempt == 6) {
                    $attempt->score = 100;
                    $point = 100;
                }elseif ($attempt->attempt == 5) {
                    $attempt->score = 90;
                    $point = 90;
                }elseif ($attempt->attempt == 4) {
                    $attempt->score = 70;
                    $point = 70;
                }elseif ($attempt->attempt == 3) {
                    $attempt->score = 50;
                    $point = 50;
                }elseif ($attempt->attempt == 2) {
                    $attempt->score = 20;
                    $point = 20;
                }elseif ($attempt->attempt == 1) {
                    $attempt->score = 10;
                    $point = 10;
                }elseif ($attempt->attempt == 0) {
                    $attempt->score = 0;
                }
            }elseif ($post == 'manual') {
                $attempt->score = 100;
                $point = 100;
            }
            if (!empty($userPoint)) {
                $userPoint->point += $point; 
            }else {
                $newUserPoint = new UserPoints();
                $newUserPoint->user_id = $user->id;
                $newUserPoint->subject = UserPoints::SUBJECT_TASK;
                $newUserPoint->point = $point;
                $newUserPoint->save();
            }
            $attempt->date = date('Y-m-d H:i:s');
            $attempt->complete = 1;
            $task->solved = 1;
            $task->attempts++;
            
            if ($full->save() && $attempt->save() && $userPoint->save() && $task->save()) {
                // Send message to user
                $message = new UserMessages();
                $message->user_id = $attempt->user_id;
                $message->task_id = $attempt->task_id;
                $message->message = "Tabriklaymiz! $user->username siz javobni to'g'ri topdingiz
                qo'lga kiritilgan ball: $attempt->score ni tashkil qiladi.";
                $message->date = date('Y-m-d H:i:s');
                $message->true = 1;
                $message->save();

                $rating = new TaskRating();
                $rating->user_id = $attempt->user_id;
                $rating->attempt = ((6 - $attempt->attempt) + 1);
                $rating->task_id = $attempt->task_id;
                $rating->date = date('Y-m-d H:i:s');
                $rating->full = 1;
                $rating->save();
                return $this->redirect(['/admin/task/messages']);
            }
        }        
        
    }


    /**
     * Displays a single Tasks model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tasks model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tasks();
        $user = Yii::$app->user->identity;
        $get = Yii::$app->request->get();
        
        if ($model->load(Yii::$app->request->post())) {
            if (empty($get) || !isset($get['id'])) {
                    $model->date = date('Y-m-d');
                    $model->sentBy_id = $user->id;
                    $model->type = $model::TYPE_TASK;
                    if ($model->save()) {
                        return $this->redirect(['view', 'id' => $model->id]);   
                    }       
               }elseif (!empty($get)) {
                    $tourModel = Tournament::findOne($get['id']);
                    $model->type = $model::TYPE_TOURNAMENT;
                    $model->tournament = $tourModel->id;
                    $model->date = date('Y-m-d');
                    $model->sentBy_id = $user->id;
                    $model->cat_id = $tourModel->category_id;
                    if ($model->save()) {
                        return $this->redirect(['tournament/view', 'id' => $tourModel->id]);   
                    } 
               }
            
        }

        return $this->render('create', [

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\user\User;
use app\models\user\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            $model->photo = UploadedFile::getInstance($model, 'photo');
            $model->password = User::generatePassword($model->password);
            $model->uploadFile();
            if ($model->validate() && $model->save(false)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->photo = UploadedFile::getInstance($model, 'photo');
            $model->password = User::generatePassword($model->password);
            $model->uploadFile();
            if ($model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/tournament/_form.php
<?php

use yii\helpers\Html;
use app\models\task\Tournament;
use yii\widgets\ActiveForm;
use zxbodya\yii2\elfinder\TinyMceElFinder;
use zxbodya\yii2\tinymce\TinyMce;
use kartik\date\DatePicker;
use pudinglabs\tagsinput\TagsinputWidget;


/* @var $this yii\web\View */
/* @var $model app\models\task\Tournament */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tournament-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="col-sm-6">
        <?//= $form->field($model, 'category_id')->dropDownList(\app\models\Tree::getCats()); ?>

        <div class="form-group field-category-parent_id has-success">
            <label class="control-label for-category_id">Raditelskaya kategoria</label>
            <select id="category-parent_id" class="form-control" name="Tournament[category_id]">
                <?= \app\components\MenuWidget::widget(['tpl' => 'select']); ?>
            </select>
        </div>
    </div>

    <div class="col-md-6">
        <?= $form->field($model, 'lang')->dropDownList(Tournament::getLang()) ?>
    </div>

    <div class="col-sm-12">
        <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    </div>
    
    <div class="col-sm-12">
        <?= $form->field($model, 'descrip')->widget(
            TinyMce::className(), [
                'settings' => [
                    'plugins' => ["advlist autolink lists link image charmap print preview hr anchor pagebreak ",
                    "searchreplace visualblocks visualchars code fullscreen",
                    "insertdatetime media nonbreaking save table contextmenu directionality",
                    "template paste textcolor "],
                    'toolbar' => "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor | fontsizeselect | tiny_mce_wiris_formulaEditor tiny_mce_wiris_formulaEditorChemistry tiny_mce_wiris_CAS",
                    'fontsize_formats' => '8px 10px 12px 14px 18px 24px 36px',],
                'fileManager' => [
                    'class' => TinyMceElFinder::className(),
                    'connectorRoute' => '/admin/tests/connector_test'
                ],
            ]
        ) ?>
    </div>

    <div class="col-sm-6">
        <?= $form->field($model, 'day')->widget(
            DatePicker::className(), [
                'name' => 'UserInfo[birthday]', 
                'value' => date("Y-m-d"),
                'options' => ['placeholder' => 'Select issue date ...'],
                'pluginOptions' => [
                  // 'dateFormat' => 'Y-m-d',
                  'todayHighlight' => true
                ],
        ]);?>
    </div>

    <div class="col-sm-6">
        <?= $form->field($model, 'time')->widget(TagsinputWidget::classname(), [
            'options' => ['class' => 'tagInput'],
            'clientOptions' => ['class' => 'tagInput'],
            'clientEvents' => []
         ]); ?>
    </div>

    <div class="col-sm-6">
        <?= $form->field($model, 'difficulty_lev')->dropDownList(Tournament::getDiffLevel()) ?>
    </div>

    <div class="col-sm-6">
        <?= $form->field($model, 'status')->dropDownList(Tournament::getStatus()); ?>
    </div>

    <div class="form-group col-sm-12">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/tournament/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\task\TournamentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tournament-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'descrip') ?>

    <?= $form->field($model, 'day') ?>

    <?php // echo $form->field($model, 'time') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'difficulty_lev') ?>

    <?php // echo $form->field($model, 'rules') ?>

    <?php // echo $form->field($model, 'sponsors') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/tournament/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\task\Tournament */

$this->title = Yii::t('app', 'Создать турнир');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Турнир'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/tournament/desactive.php
<?php 

use yii\helpers\Url;

$flashM = explode(',', Yii::$app->session->getFlash('has-active'));
$selectedId = $flashM[0];
$selectedDate = $flashM[1];

?>

<div class="box box-primary">
  <?php if (Yii::$app->session->hasFlash('has-active')) { ?>
    <div class="box-body">
      <div class="callout callout-warning">
          <h4>Diqqat!</h4>
          <p>Hozirgi holatda faol turnir mavjud</p>
          <p><a href="/admin/tournament/">Shu holida qolsin</a></p>
          <a href="<?=Url::to(['/admin/tournament/desactive', 'checkedId' => $selectedId, 'checkedDate' => $selectedDate ])?>" class="btn btn-primary">Tanlangan turnir faollashsin!</a>
        </div>
    </div>
  <?php }elseif (Yii::$app->session->hasFlash('done-active')) { ?>
    <div class="box-body">
      <div class="callout callout-success">
          <h3>Turnir faollashtirildi!</h3>
          <h4><?= 'Nomi:  '.$tournAct->name?></h4>
          <h4><?= 'Kuni:  '.$tournAct->day?></h4>
          
        </div>
    </div>
  <?php } ?>
  <div class="box-header">
    <i class="ion ion-clipboard"></i>

    <h3 class="box-title">Aktivlashtirilmagan Turnirlar</h3>

    <div class="box-tools pull-right">
      <ul class="pagination pagination-sm inline">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">&raquo;</a></li>
      </ul>
    </div>
  </div>
  <!-- /.box-header -->
  <form action="<?= Url::to('/ru/admin/tournament/desactive')?>" method="post">
    <?= yii\helpers\Html::hiddenInput(\Yii::$app->getRequest()->csrfParam, \Yii::$app->getRequest()->getCsrfToken(), []);?>
  <div class="box-body">
    <!-- See dist/js/pages/dashboard.js to activate the todoList plugin -->
    <ul class="todo-list">
      <?php foreach ($tournDesAct as $key => $tourn) { ?>
          <li id="li-<?=$tourn->id?>">
            <input type="radio" name="tournId" class="editor" data-id="<?=$tourn->id?>" value="<?=$tourn->id?>">
            <span class="text" style="font-size: 15px;"><?= $tourn->name?></span>
            <!-- Emphasis label -->
            <small class="label label-danger" id="date<?=$tourn->id?>" style="font-size: 11px;"><!-- <i class="fa fa-clock-o"></i> --><?= $tourn->day?></small>
            <div class="col-md-3 pull-right" id="edit_date<?=$tourn->id?>"></div>
            <!-- General tools such as edit or delete-->
            <div class="tools">
              <!-- <i class="fa fa-edit" ></i> -->
              <!-- <i class="fa fa-trash-o"></i> -->
            </div>
          </li>
      <?php } ?>
    </ul>
  </div>
  <!-- /.box-body -->
  <div class="box-footer clearfix no-border">
    <button type="submit" class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add item</button>
  </div>
  </form>
</div>

modules/admin/views/tournament/list-result.php
<?php 

use app\models\user\User;

?>

<div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title"><?= $tourn->name?></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="table-responsive">
        <table class="table no-margin">
          <thead>
          <tr>
            <th>ID</th>
            <th>Участник</th>
            <th>Страна</th>
            <th>Балл</th>
            <th>Место</th>
          </tr>
          </thead>
          <tbody>
            <?php $num = 1; foreach ($listResult as $key => $result) { 
                $user = User::findOne($result->user_id);
            ?>
                <tr>
                  <td><?= $num; ?></td>
                  <td><a href="pages/examples/invoice.html"><?= $user->username ?></a></td>
                  <td><?= $result->country  ?></td>
                  <td><?= $result->score ?>  <span class="label label-success">(из 60)</span></td>
                  <td>
                    <div class="sparkbar" data-color="#00a65a" data-height="20"><?= $num?></div>
                  </td>
                </tr>
            <?php $num++; } ?>
          
          
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix">
      <a href="/admin/tournament/" class="btn btn-sm btn-info btn-flat pull-left">Ortga</a>
      <!-- <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a> -->
    </div>
    <!-- /.box-footer -->
</div>

modules/admin/views/tournament/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\task\Tournament */

$this->title = Yii::t('app', 'Обновить Турнир: {nameAttribute}', [
    'nameAttribute' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Турнир'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Обновить');
?>
<div class="box container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/tournament/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use app\models\category\Category;
use app\models\user\User;
use app\models\task\Tournament;

/* @var $this yii\web\View */
/* @var $model app\models\task\Tournament */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Турнир'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if ($model->status == Tournament::STATUS_PAST): ?>
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">NATIJALAR</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="table-responsive">
            <table class="table no-margin">
              <thead>
              <tr>
                <th>ID</th>
                <th>Участник</th>
                <th>Страна</th>
                <th>Балл</th>
                <th>Место</th>
              </tr>
              </thead>
              <tbody>
                <?php $num = 1; foreach ($listResult as $key => $result) { 
                    $user = User::findOne($result->user_id);
                ?>
                    <tr>
                      <td><?= $num; ?></td>
                      <td><?= $user->username ?></td>
                      <td><?= $result->country  ?></td>
                      <td><?= $result->score ?>  <span class="label label-success">(из 60)</span></td>
                      <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20"><?= $num?></div>
                      </td>
                    </tr>
                <?php $num++; } ?>
              
              
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <a href="/admin/tournament/" class="btn btn-sm btn-info btn-flat pull-left">Ortga</a>
          <!-- <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a> -->
        </div>
        <!-- /.box-footer -->
    </div>
    <?php endif ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Tasks'), ['/admin/task/create', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'category_id',
                'value' => function($data){
                    $category = Category::findOne($data->category_id);
                    return $category->name;
                },
                'contentOptions' => ['style' => 'width:800px;'],
            ],
            'lang',
            'name',
            'descrip:html',
            'day',
            'time',
            'status',
            'difficulty_lev',
            'rules',
            'sponsors',
        ],
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'cat_id',
                'value' => function($data){
                    $user = Category::findOne($data->cat_id);
                    return $user->name;
                },
                'contentOptions' => ['style' => 'width:100px;'],
            ],
            
            [
                'attribute' => 'sentBy_id',
                'value' => function($data){
                    $user = User::findOne($data->sentBy_id);
                    return $user->username;
                },
                'contentOptions' => ['style' => 'width:100px;'],
            ],
            [
                'attribute' => 'name',
                'contentOptions' => ['style' => 'width:250px;'],
            ],
            [
                'attribute' => 'task',
                'format' => 'html',
                'value' => function($data) {
                    return substr($data->task, 0, 200);
                },
                'contentOptions' => ['style' => 'width:250px;'],
            ],
            // 'short_answ',
            'lang',
            //'source',
            //'level',
            //'class',
            //'bal',
            'theme',
            'date',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'headerOptions' => ['style' => 'color:#337ab7'],
                'template' => '{view}{update}{delete}',
                'buttons' => [
                'view' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                'title' => Yii::t('app', 'lead-view'),
                    ]);
                },

                'update' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                'title' => Yii::t('app', 'lead-update'),
                    ]);
                },
                'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                                'title' => Yii::t('app', 'lead-delete'),
                    ]);
                }

                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        $url =['task/view', 'id' => $model->id];
                        return $url;
                }

                if ($action === 'update') {
                    $url =['task/update', 'id' => $model->id];
                    return $url;
                }
                if ($action === 'delete') {
                    $url =['task/delete', 'id' => $model->id];
                    return $url;
                }

                }
                  
            ],
        ],
    ]); ?>

</div>