models/Result.php
<?php 

namespace app\models;

use yii\db\ActiveRecord;

Class Result extends ActiveRecord
{
	public static function tableName(){
		return 'statistics';
	}

	public function addResults($quest_id, $pred_name, $var_id, $user)
	{

		if (isset($_SESSION['result'][$user->username][$pred_name][$quest_id])) {
			$old = $_SESSION['result'][$user->username][$pred_name][$quest_id];
			$_SESSION['result'][$user->username][$pred_name][$quest_id] = $var_id;

		}elseif (isset($_SESSION['result'][$user->username][$pred_name])) {
			$_SESSION['result'][$user->username][$pred_name][$quest_id] = $var_id;
		
		}elseif (!isset($_SESSION['result'][$user->username][$pred_name])) {
			$_SESSION['result'][$user->username][$pred_name] = [$quest_id => $var_id];

		}else {
			$_SESSION['result'] = [
                'user_id' => $user->id,
                'startTime' => date('H:i:s'),
                'stopTime' => 0,
                'max_ball' => 0,
                $user->username => [
                        $pred_name => [ $quest_id => $var_id ],
                    ],
            ];
		}
		return $_SESSION['result'];

	}
	
}

controllers/ResultsController.php
<?php 

namespace app\controllers;

use Yii;
use DateTime;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use app\models\user\User;
use app\models\user\UserStats;
use app\models\tests\Tests;
use app\models\tests\TestVariant;
use app\models\Result;
use app\models\cours\Cours;
use app\models\testblog\TestBlog;
use app\models\statistics\Statistics;
use yii\helpers\ArrayHelper;
use yii\data\Pagination;

/**
* 
*/
class ResultsController extends Controller
{
	
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = Yii::$app->user->identity;
        $modelUser = User::find()->with('results', 'useBlogs')->where(['id' => $user->id])->one();
        $userResults = Statistics::find()->where(['user_id' => $user->id]);
        
        $countQuery = clone $userResults;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'defaultPageSize' => 14,
            'forcePageParam' => false, 
            'pageSizeParam' => false,
        ]);
        $models = $userResults->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy('date DESC')
            ->all();

        return $this->render('index', [
            'user' => $user,
            'modelUser' => $modelUser,
            'models' => $models,
            'pages' => $pages
            //'modelStats' => $modelStats,
        ]);
    }

    public function actionStats() 
    {
        $user = Yii::$app->user->identity;
        $modelStats = Statistics::find()
        ->select(['DATE_FORMAT(date, "%Y %m" ) as month, SUM(correct_answer) as sum_correct, 
            SUM(`interval`) as sum_interval, SUM(wrong_answer) as sum_wrong'])
        ->where(['user_id' => $user->id])
        // ->andWhere(['<=','DATE(date)', date('Y')."-03-30"])
        ->groupBy('month')
        ->asArray()
        ->all();

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        return $modelStats;
    }

    public function actionAddToResults()
    {
        $this->layout = false;
        $user = \Yii::$app->user->identity;
        $var_id = Yii::$app->request->get('var_id');
        $quest_id = Yii::$app->request->get('quest_id');
        $pred_name = Yii::$app->request->get('pred_name');

        $result = new Result();
        $result->addResults($quest_id, $pred_name, $var_id, $user);
        
        echo "<pre>";
        print_r($_SESSION['result']);
        echo "</pre>";

    }

    public function actionResult()
    {

        $user = \Yii::$app->user->identity;
        if ($_SESSION['result']['stopTime'] == 0) {
            $_SESSION['result']['stopTime'] = date("H:i:s");
        }
        if (empty($_SESSION['result']['all'])) {
            if (isset($_SESSION['result'][$user->username])) {
                $check = [];
                foreach ($_SESSION['result'][$user->username] as $pred => $arrAnsw) {
                    $check[$pred];
                    foreach ($arrAnsw as $quest_id => $var_id) {
                        $correct = TestVariant::find()->where(['test_id' => $quest_id])->andWhere(['correct' => 1])->one();
                        $selected = TestVariant::find()->where(['test_id' => $quest_id])->andWhere(['id' => $var_id])->one();
                        if ($correct->id == $selected->id) {
                                $check[$pred]['true'] += 1;
                                $_SESSION['result']['all']['true'] += 1;
                        }else {
                                $check[$pred]['false'] += 1;
                                $_SESSION['result']['all']['false'] += 1;
                        }
                    }
                }
                $_SESSION['result']['checked'] = $check;
            }else {
                return $this->redirect(['/site/login']);
            }
        }
        return $this->render('result', [
                'result' => $result,
                // 'predmet_1' => $predmet_1,
                // 'predmet_2' => $predmet_2,
                // 'predmet_3' => $predmet_3,
                // 'blogModels' => $blogModels,
            ]);
    }

    public function actionSave()
    {
        $user = \Yii::$app->user->identity;

        if (!$_SESSION['result']['saved'] == true) {
            $predmets = [];
            foreach ($_SESSION['result'][$user->username] as $namePred => $arrAnsw) {
                if (empty($predmets)){ $predmets[0] = $namePred;}elseif (!empty($predmets[0]) && empty($predmets[1])) { $predmets[1] = $namePred; }elseif (!empty($predmets[0]) && !empty($predmets[1])) { $predmets[2] = $namePred; }
                
                foreach ($arrAnsw as $quest => $value) {
                    $userstatsModel = new UserStats();
                    $userstatsModel->user_id = $user->id;
                    $userstatsModel->blog_id = $namePred;
                    $userstatsModel->quest_id = $quest;
                    $userstatsModel->select_id = $value;
                    $userstatsModel->start_time = $_SESSION['result']['startTime'];
                    $userstatsModel->stop_time = $_SESSION['result']['stopTime'];
                    $userstatsModel->date = date('Y-m-d, H:i:s');
                    $userstatsModel->save();
                }
            }

            $date1 = new DateTime($_SESSION['result']['startTime']);
            $date2 = new DateTime($_SESSION['result']['stopTime']);
            $interval = $date2->diff($date1);
            $time = $date2->getTimestamp() - $date1->getTimestamp();

            $statsModel = new Statistics();
            $statsModel->user_id = $user->id;
            $statsModel->start_time = $_SESSION['result']['startTime'];
            $statsModel->stop_time = $_SESSION['result']['stopTime'];
            $statsModel->interval = $time;
            $statsModel->correct_answer = $_SESSION['result']['all']['true'] ? $_SESSION['result']['all']['true'] : 0 ;
            $statsModel->wrong_answer = $_SESSION['result']['all']['false'] ? $_SESSION['result']['all']['false'] : 0 ;
            $statsModel->date = date('Y-m-d, H:i:s');
            $statsModel->predmet1 = mb_substr($predmets[0], 0, -1);
            $statsModel->predmet2 = mb_substr($predmets[1], 0, -1);
            $statsModel->predmet3 = mb_substr($predmets[2], 0, -1);
            if ($statsModel->save()) {
                $session = Yii::$app->session;
                $session->open();
                $session->remove('result');
                $_SESSION['result'] = ['saved' => 'true'];
                
            }

            \Yii::$app->getSession()->setFlash('success', Yii::t('lang', 'Ваши результаты сохранены, и вы можете увидеть свои результаты в разделе «Мои результаты».'));
            return $this->redirect(['/test/premium-filter']);
        }
        return $this->redirect(['/test/premium-filter']);
         
    }

    public function actionDelete()
    {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('result');
        if (empty($_SESSION['result'])) {
            \Yii::$app->getSession()->setFlash('deleted', Yii::t('lang', "Результаты теста удалены, вы можете увидеть сохраненные результаты в разделе «Мои результаты»"));
            return $this->redirect(['/test/premium-filter']);
        }
        // $this->layout = false;
        // return $this->render('result', [
        //         'result' => $result,
        // ]);
    }
}

controllers/TestController.php
<?php 

namespace app\controllers;

use Yii;
use app\models\tests\Tests;
use app\models\testblog\TestGroup;
use app\models\testblog\TestBlog;
use app\models\category\Category;
use app\models\cours\Cours;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\helpers\ArrayHelper;

/**
* 
*/
class TestController extends Controller
{
	
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionModal()
    {

        $modelTestGroup = TestGroup::find()->all();

        $free = Yii::$app->request->post(2);
        $premium = Yii::$app->request->post(3);

        if ($free) {
            echo $free;
        }else {
            echo $premium;
        }


        $this->layout = false;
        return $this->render('modal', [
            'modelTestGroup' => $modelTestGroup,
        ]);
    }

    public function actionIndex()
    {

        // $model = Category::getCats();
        $model_cours = Cours::getCours();

        return $this->render('index', [
            // 'model' => $model,
            'model_cours' => $model_cours
        ]);
    }

    public function actionFreeTest()
    {
        $user = \Yii::$app->user->identity;        
        $test = Tests::find()->with('variants')->where(['lang' => Yii::$app->language])->limit(30)->orderBy('rand()')->all();
        $session = Yii::$app->session;
        $session->open();

        $_SESSION['result'] = [
                'user_id' => $user->id,
                'type' => 'free',
                'startTime' => date('H:i:s'),
                'stopTime' => 0,
                'max_ball' => 0,
                // $user->username => [],
            ];

        return $this->render('free-test', [
                'test' => $test,
            ]);

    }



    public function actionPremiumFilter()
    {
        $test = Tests::find()->all();
        $test_count = count($test);
        

        unset($_SESSION['tests']);
        return $this->render('premium-filter', [
            'test_count' => $test_count,
        ]);
    }



    public function actionPremiumTest()
    {
        $user = \Yii::$app->user->identity;
        $lang = Yii::$app->language;
        
        if (Yii::$app->request->post()) {
            $lang = Yii::$app->request->post('lang');
            $level = Yii::$app->request->post('level');
            $predmet1 = Yii::$app->request->post('predmet1');
            $predmet2 = Yii::$app->request->post('predmet2');
            $predmet3 = Yii::$app->request->post('predmet3');
            
            if (!empty($lang) && !empty($level) && !empty($predmet1) && empty($predmet2) && empty($predmet3)) {
                $test = [];
                $mainCat = Category::findOne($predmet1);
                $tests = Tests::find()->with('variants')->where(['category_id' => $predmet1])->andWhere(['lang' => $lang])->andWhere(['level' => $level])->orderBy('rand()')->limit(30)->all();
                $test['mainCat'] = $mainCat;
                $test['tests'] = $tests;
                
                $session = Yii::$app->session;
                $session->open();
                $_SESSION['result'] = [
                    'user_id' => $user->id,
                    'type' => 'school',
                    'startTime' => date('H:i:s'),
                    'stopTime' => 0,
                    'bal' => 0,
                    // $user->username => [],
                ];

                return $this->render('premium-test', [
                    'test' => $test
                ]);

            }elseif (!empty($lang) && !empty($level) && !empty($predmet1) && !empty($predmet2) && !empty($predmet3)) {
                    $test1 = Tests::getTests($predmet1, $level, $lang);
                    $used_ids_1 = ArrayHelper::map($test1['tests'], 'id', 'id');
                    $test2 = Tests::getTests($predmet2, $level, $lang, $used_ids_1);
                    $used_ids_2 = ArrayHelper::map($test2['tests'], 'id', 'id');
                    $test3 = Tests::getTests($predmet3, $level, $lang, $used_ids_1, $used_ids_2);
                    
                    $session = Yii::$app->session;
                    $session->open();
                    $_SESSION['result'] = [
                        'user_id' => $user->id,
                        'type' => 'student',
                        'startTime' => date('H:i:s'),
                        'stopTime' => 0,
                        'bal' => 0,
                        // $user->username => [],
                    ];
                    
                    return $this->render('premium-test', [
                        'test1' => $test1,
                        'test2' => $test2,
                        'test3' => $test3,
                    ]);
            }else {
                echo '<pre>';
                print_r('error! at the abiturient request');
                echo '</pre>';
                exit();
            }

        }else {
            return $this->redirect(["/test/premium-filter"]); 
        }
        
    }

    public function actionRemoveVariant()
    {
        $user = Yii::$app->user->identity;
        $questId = Yii::$app->request->post();
        $sessionArr = $_SESSION['result'][$user->username]; 
        foreach ($sessionArr as $key => $pred) {
            foreach ($pred as $quest_id => $varId) {
                if ($quest_id == $questId['questId']) {
                    unset($_SESSION['result'][$user->username][$key][$quest_id]);
                }
            }
        }
        
        return json_encode($questId);
    }

    public function actionTests()
    {
        return $this->render('tests');
    }

    public function actionCatId()
    {
        $mainCats = Category::find()->where(['parent_id' => 0])->all();
        $arr = ArrayHelper::map($mainCats, 'id', 'id');
        return json_encode(['kkk' => $arr]);
        // foreach ($mainCats as $key => $value) {
        //     $subCats = Category::find()->where(['parent_id' => $value->id])->all();
        // }
    }
}

views/results/result.php
<?php
use yii\helpers\Url;
	$user = \Yii::$app->user->identity;

	// get time
	$date1 = new DateTime($_SESSION['result']['startTime']);
	$date2 = new DateTime($_SESSION['result']['stopTime']);
	$interval = $date2->diff($date1);
	$hour = $interval->format("%h");
	$min = $interval->format("%i");
	$sec = $interval->format("%s");

	$true = $_SESSION['result']['all']['true'] ? $_SESSION['result']['all']['true'] : 1;
	$false = $_SESSION['result']['all']['false'] ? $_SESSION['result']['all']['false'] : 1;
	$percentTrue = ($true * 100) / ($false + $true);
	$percentFalse = 100 - $percentTrue;	
?>
<style type="text/css">
.GaugeMeter {
  position: relative;
  text-align: center;
  overflow: hidden;
  cursor: default;
  display: inline-block;
}

.GaugeMeter span, .GaugeMeter b {
  width: 54%;
  position: absolute;
  text-align: center;
  display: inline-block;
  color: rgba(0,0,0,.8);
  font-weight: 100;
  font-family: "Open Sans", Arial;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  margin: 0 23%;
}

.GaugeMeter[data-style="Semi"] b {
  width: 80%;
  margin: 0 10%;
}

.GaugeMeter s, .GaugeMeter u {
  text-decoration: none;
  font-size: .60em;
  font-weight: 200;
  opacity: .6;
}

.GaugeMeter b {
  color: #000;
  font-weight: 200;
  opacity: .8;
}
</style>
<?php if (!isset($_SESSION['result']['saved']) && isset($_SESSION['result'])) { ?>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	<div class="">
	<div class="col-md-10 col-md-offset-1" style="min-height: 637px; margin-top: 70px;">
		<div class="col-md-7 col-md-offset-0">
			<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6" style="">
	            <div class="GaugeMeter gaugeMeter" id="PreviewGaugeMeter_4" 
	            data-percent="<?= intval($percentFalse) ?>" 
	            data-append="%" 
	            data-size="190" 
	            data-theme="green" 
	            data-back="RGBa(22,22,22,.1)" 
	            data-animate_gauge_colors="1" 
	            data-animate_text_colors="1" 
	            data-width="5"
	            data-label_color="#FFF" 
	            data-stripe="2" 
	            data-id="PreviewGaugeMeter_4" 
	            style="width: 180px; margin-left: 29px; "><span style="line-height: 193px;  color: #2980b9; font-size: 39.6px;"><?= intval($percentFalse) ?><u>%</u></span><canvas width="180" height="180"></canvas></div>
	            <span class="text-center col-md-11 col-sm-8 col-xs-8 col-lg-10" style="margin-left: 10%; color: #696969;">
	            	<span class=" text-center" style="font-size: 25px; color:#D83C3B; margin: 10px auto;"><?= $_SESSION['result']['all']['false'] ? $_SESSION['result']['all']['false'] : 0 ?>
	            	</span><br>
	            	<span style="margin: 10px auto;"><?=Yii::t('lang', 'uncorrect')?></span>
	            </span>
	        </div>
		
			<div class="col-lg-6 col-md-6 col-xs-12 col-sm-6" style="">
	            <div class="GaugeMeter gaugeMeter" id="PreviewGaugeMeter_4" 
	            data-percent="<?= intval($percentTrue) ?>" 
	            data-append="%" 
	            data-size="190" 
	            data-theme="green" 
	            data-back="RGBa(22,22,22,.1)" 
	            data-animate_gauge_colors="1" 
	            data-animate_text_colors="1" 
	            data-width="5"
	            data-label_color="#696969"
	            data-stripe="2" 
	            data-id="PreviewGaugeMeter_4" 
	            style="width: 180px; margin-left: 29px;"><span style="line-height: 193px;  color: #2980b9; font-size: 39.6px;"><?= intval($percentTrue) ?><u>%</u></span><canvas width="180" height="180"></canvas></div>
	            <span class="text-center col-md-11 col-sm-8 col-xs-8 col-lg-10" style="margin-left: 10%; color: #696969;">
	            	<span class=" col-lg-12 text-center" style="font-size: 25px; color:#93de93;"><?= $_SESSION['result']['all']['true'] ? $_SESSION['result']['all']['true'] : 0?></span>
	            	<br>
	            	<span style=" margin: 10px auto;"><?=Yii::t('lang', 'correct')?></span>
	            </span>
	        </div>
		</div>
		<div class="col-lg-5 col-md-5 col-xs-12 col-sm-8" style="">
            <div class="" style="border-left: 1px dashed #ccc; height: 210px; padding: 15px 0 0 40px; margin-left: 30px; margin-top: 40px;  ">
            	<h4 style="color: #696969;">
            		<?=Yii::t('lang', 'question')?> : <span style="color:#3498db; font-size: 21px;"><?= $_SESSION['result']['all']['true'] + $_SESSION['result']['all']['false']?></span>
            	</h4>
            	<h4 style="color: #696969;">
            		<?=Yii::t('lang', 'correct')?> : <span style="color:#3498db; font-size: 21px;"><?= $_SESSION['result']['all']['true'] ? $_SESSION['result']['all']['true'] : 0?></span>
            	</h4>
            	<h4 style="color: #696969;">
            		<?=Yii::t('lang', 'uncorrect')?> : <span style="color:#3498db; font-size: 21px;"><?= $_SESSION['result']['all']['false'] ? $_SESSION['result']['all']['false'] : 0 ?></span>
            	</h4>
            	<h4 style="color: #696969;">
            		<?=Yii::t('lang', 'dateres')?> : <span style="color:#3498db; font-size: 21px;">
            		<?= '0'.$hour.' : '.(($min < 10 ) ? '0'.$min : $min).' : '. (($sec < 10 ) ? '0'.$sec : $sec) ?> </span>
            	</h4>
            	<!-- <h4 style="color: #696969;">
            		Бал : <span style="color:#3498db; font-size: 21px;"></span>
            	</h4> -->
            </div>
        </div>

        <div class="col-md-11 col-lg-11 col-sm-11 col-xs-11" style="margin-top: 70px;">
          <table class="table table-striped text-center">
            <thead>
              <tr>
              	<?php foreach ($_SESSION['result']['checked'] as $predName => $resArr) { ?>
	                <th style="font-size: 20px;"><?= mb_substr($predName, 0, -1); ?></th>
	            <?php } ?>
              </tr>
            </thead>
            <tbody>
            	<tr>
            	<?php foreach ($_SESSION['result']['checked'] as $predName => $resArr) { ?>
	  	            <td><span><?=Yii::t('lang', 'correct')?> -</span> <?= $resArr['true'] ? $resArr['true'] : 0 ?> </td>
  	          	<?php } ?>
				</tr>
				<tr>
            	<?php foreach ($_SESSION['result']['checked'] as $predName => $resArr) { ?>
	  	            <td><span><?=Yii::t('lang', 'uncorrect')?> -</span> <?= $resArr['false'] ? $resArr['false'] : 0 ?> </td>
  	          	<?php } ?>
				</tr>              
            </tbody>
          </table>
        </div>
        <?php 
        	$lang = \Yii::$app->language;
        	if ($_SESSION['result']['type'] != 'free') { ?>
		        <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12" style="margin-top: 70px; margin-bottom: 30px;">
		        	<a href='<?= Url::to(["$lang/results/delete"])?>'>
		        	<button class="btn btn-danger" ><?= Yii::t('lang', 'deleteres') ?></button></a>
		        	<a href='<?= Url::to(["$lang/results/save"])?>'>
					<button class="btn btn-success"><?= Yii::t('lang', 'saveres') ?></button></a>
				</div>
		<?php }else { ?>
			<div class="col-md-12" style="margin-top: 70px; margin-bottom: 30px;">
	        	<a href='<?= Url::to(["/"])?>'>
	        	<button class="btn btn-default" ><?= Yii::t('lang', 'to_home') ?></button></a>
	        	<a href='<?= Url::to(["/test/index"])?>'>
				<button class="btn btn-success"><?= Yii::t('lang', 'tariffs') ?></button></a>
			</div>
		<?php } ?>
	</div>
</div>

<?php } elseif ($_SESSION['result']['saved'] == true) { ?>
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center " style=" padding-top: 20px; padding-bottom: 20px;" >
			<img src="/images/save-1.png" style="width: 200px; height: 200px;">
			<span style="color: #7d7c7c; font-size: 25px; margin-left: 25px; font-weight: bold; margin-top: 10px;"><?=Yii::t('lang', 'savedres')?></span>
		</div>
	</div>	
<?php  }elseif (empty($_SESSION['result'])) { ?>
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center" >
			<img src="/images/delete-1.png" style="width: 200px; height: 200px;">
			<span style="color: #7d7c7c; margin-top: 10px;font-size: 25px; margin-left: 20px; font-weight: bold;"><?=Yii::t('lang', 'deleteres')?></span>
		</div>
	</div>	
<?php }elseif (empty($_SESSION['result'][Yii::$app->user->identity->username])) { ?>
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center" >
			<!-- <img src="/images/delete-1.png" style="width: 200px; height: 200px;"> -->
			<span style="color: #7d7c7c; margin-top: 10px;font-size: 25px; margin-left: 20px; font-weight: bold;"><?=Yii::t('lang', 'you_are_dont_answered_no_one_questions')?></span>
		</div>
	</div>	
<?php } ?>